### ISSUE TITLE
Sync Adapter addon

### ISSUE THREAD

**Issue by alou-S** [FriendlyNeighborhoodShane/MinMicroG-abuse-github#6]
Is it possible to create a separate module for Google Sync Adapters or add it to the IAP/Minimal builds? 

Some people would want Sync Adapters without the Aurora stuff.

**Comment by FriendlyNeighborhoodShane** [comment]
Hi,
Sorry for the late reply. I haven't been able to pay attention to this repo recently.
I made an addon for it if you still want it:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/download/2023.07.29/MinAddon-SyncAdapters-Sync-UPDATELY-20230729171631.zip

I haven't added it to list of variants that will be built continuouslt though, because I don't think it will be updated very much.
